name: .NET
#GLOBAL ENVIRONMENT VARIABLES
env:
   APPLICATION_NAME    : "Remind_Web_App"
   DEPLOY_PACKAGE_NAME : "REMIND-DEPLOY-VERSION-${{ github.sha }}"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  result:
    needs: build  # Ensures that the result job runs after the build job
    runs-on: ubuntu-latest
    steps:
    - name: Print message
      run: echo "Congratulations, the build was successful!"

  help:
    needs: result  # Ensures that the result job runs after the build job
    runs-on: ubuntu-latest
    steps:
    - name: Print version
      run: echo "${{env.APPLICATION_NAME}} with version ${{env.DEPLOY_PACKAGE_NAME}}"
#Scope variables
  path:
    needs: help  # Ensures that the path job runs after the help job
    env:
      scope_path_1: "Content of current folder"
      scope_path_2: "Linux Area"
    runs-on: ubuntu-latest
    steps:
      - name: List current folder
        run: echo "Get Scope variables:(${{env.scope_path_1} / ${{env.scope_path_2})}"
      - name: List directory contents
        run: ls -lah


